### ISSUE TITLE
DateTimeFormat Playground options is missing a year option

### ISSUE THREAD

**Issue by quiqueg** [jesperorb/intl-explorer#61]
**Describe the bug**

The [Playground page for DateTimeFormat](https://www.intl-explorer.com/Playground?locale=en-US&schema=eyJzY2hlbWEiOnsibWV0aG9kIjoiRGF0ZVRpbWVGb3JtYXQiLCJwcmltYXJ5Rm9ybWF0dGVyIjoiZm9ybWF0IiwiaW5wdXRWYWx1ZXMiOlsiMjAyMi0wNC0yNFQxOTowMCIsIjIwMjItMTAtMjRUMTk6MDAiXSwiaW5wdXRWYWx1ZVR5cGUiOiJkYXRlIiwic2Vjb25kYXJ5Rm9ybWF0dGVycyI6WyJmb3JtYXRUb1BhcnRzIiwiZm9ybWF0UmFuZ2UiLCJmb3JtYXRSYW5nZVRvUGFydHMiXSwiaW52YWxpZE9wdGlvbkNvbWJvcyI6eyJkYXRlU3R5bGU6bG9uZyI6WyJkYXkiLCJob3VyIiwibWludXRlIiwic2Vjb25kIiwid2Vla2RheSIsIm1vbnRoIiwiZXJhIiwiZGF5UGVyaW9kIiwidGltZVpvbmVOYW1lIiwiZnJhY3Rpb25hbFNlY29uZERpZ2l0cyJdLCJkYXRlU3R5bGU6ZnVsbCI6WyJkYXkiLCJob3VyIiwibWludXRlIiwic2Vjb25kIiwid2Vla2RheSIsIm1vbnRoIiwiZXJhIiwiZGF5UGVyaW9kIiwidGltZVpvbmVOYW1lIiwiZnJhY3Rpb25hbFNlY29uZERpZ2l0cyJdLCJkYXRlU3R5bGU6bWVkaXVtIjpbImRheSIsImhvdXIiLCJtaW51dGUiLCJzZWNvbmQiLCJ3ZWVrZGF5IiwibW9udGgiLCJlcmEiLCJkYXlQZXJpb2QiLCJ0aW1lWm9uZU5hbWUiLCJmcmFjdGlvbmFsU2Vjb25kRGlnaXRzIl0sImRhdGVTdHlsZTpzaG9ydCI6WyJkYXkiLCJob3VyIiwibWludXRlIiwic2Vjb25kIiwid2Vla2RheSIsIm1vbnRoIiwiZXJhIiwiZGF5UGVyaW9kIiwidGltZVpvbmVOYW1lIiwiZnJhY3Rpb25hbFNlY29uZERpZ2l0cyJdLCJ0aW1lU3R5bGU6bG9uZyI6WyJkYXkiLCJob3VyIiwibWludXRlIiwic2Vjb25kIiwid2Vla2RheSIsIm1vbnRoIiwiZXJhIiwiZGF5UGVyaW9kIiwidGltZVpvbmVOYW1lIiwiZnJhY3Rpb25hbFNlY29uZERpZ2l0cyJdLCJ0aW1lU3R5bGU6ZnVsbCI6WyJkYXkiLCJob3VyIiwibWludXRlIiwic2Vjb25kIiwid2Vla2RheSIsIm1vbnRoIiwiZXJhIiwiZGF5UGVyaW9kIiwidGltZVpvbmVOYW1lIiwiZnJhY3Rpb25hbFNlY29uZERpZ2l0cyJdLCJ0aW1lU3R5bGU6bWVkaXVtIjpbImRheSIsImhvdXIiLCJtaW51dGUiLCJzZWNvbmQiLCJ3ZWVrZGF5IiwibW9udGgiLCJlcmEiLCJkYXlQZXJpb2QiLCJ0aW1lWm9uZU5hbWUiLCJmcmFjdGlvbmFsU2Vjb25kRGlnaXRzIl0sInRpbWVTdHlsZTpzaG9ydCI6WyJkYXkiLCJob3VyIiwibWludXRlIiwic2Vjb25kIiwid2Vla2RheSIsIm1vbnRoIiwiZXJhIiwiZGF5UGVyaW9kIiwidGltZVpvbmVOYW1lIiwiZnJhY3Rpb25hbFNlY29uZERpZ2l0cyJdfSwib3B0aW9ucyI6W3sibmFtZSI6ImRhdGVTdHlsZSIsInZhbHVlVHlwZSI6InN0cmluZyIsImlucHV0VHlwZSI6InNlbGVjdCJ9LHsibmFtZSI6InRpbWVTdHlsZSIsInZhbHVlVHlwZSI6InN0cmluZyIsImlucHV0VHlwZSI6InNlbGVjdCJ9LHsibmFtZSI6ImRheSIsInZhbHVlVHlwZSI6InN0cmluZyIsImlucHV0VHlwZSI6InNlbGVjdCJ9LHsibmFtZSI6ImhvdXIiLCJ2YWx1ZVR5cGUiOiJzdHJpbmciLCJpbnB1dFR5cGUiOiJzZWxlY3QifSx7Im5hbWUiOiJtaW51dGUiLCJ2YWx1ZVR5cGUiOiJzdHJpbmciLCJpbnB1dFR5cGUiOiJzZWxlY3QifSx7Im5hbWUiOiJzZWNvbmQiLCJ2YWx1ZVR5cGUiOiJzdHJpbmciLCJpbnB1dFR5cGUiOiJzZWxlY3QifSx7Im5hbWUiOiJ3ZWVrZGF5IiwidmFsdWVUeXBlIjoic3RyaW5nIiwiaW5wdXRUeXBlIjoic2VsZWN0In0seyJuYW1lIjoibW9udGgiLCJ2YWx1ZVR5cGUiOiJzdHJpbmciLCJpbnB1dFR5cGUiOiJzZWxlY3QifSx7Im5hbWUiOiJlcmEiLCJ2YWx1ZVR5cGUiOiJzdHJpbmciLCJpbnB1dFR5cGUiOiJzZWxlY3QifSx7Im5hbWUiOiJkYXlQZXJpb2QiLCJ2YWx1ZVR5cGUiOiJzdHJpbmciLCJpbnB1dFR5cGUiOiJzZWxlY3QifSx7Im5hbWUiOiJob3VyQ3ljbGUiLCJ2YWx1ZVR5cGUiOiJzdHJpbmciLCJpbnB1dFR5cGUiOiJzZWxlY3QifSx7Im5hbWUiOiJob3VyMTIiLCJ2YWx1ZVR5cGUiOiJib29sZWFuIiwiaW5wdXRUeXBlIjoicmFkaW8ifSx7Im5hbWUiOiJjYWxlbmRhciIsInZhbHVlVHlwZSI6InN0cmluZyIsImlucHV0VHlwZSI6InNlbGVjdCJ9LHsibmFtZSI6ImZyYWN0aW9uYWxTZWNvbmREaWdpdHMiLCJ2YWx1ZVR5cGUiOiJudW1iZXIiLCJpbnB1dFR5cGUiOiJ0ZXh0IiwibWF4IjozLCJtaW4iOjB9LHsibmFtZSI6Im51bWJlcmluZ1N5c3RlbSIsInZhbHVlVHlwZSI6InN0cmluZyIsImlucHV0VHlwZSI6InNlbGVjdCJ9LHsibmFtZSI6InRpbWVab25lTmFtZSIsInZhbHVlVHlwZSI6InN0cmluZyIsImlucHV0VHlwZSI6InNlbGVjdCJ9LHsibmFtZSI6ImxvY2FsZU1hdGNoZXIiLCJ2YWx1ZVR5cGUiOiJzdHJpbmciLCJpbnB1dFR5cGUiOiJzZWxlY3QifSx7Im5hbWUiOiJmb3JtYXRNYXRjaGVyIiwidmFsdWVUeXBlIjoic3RyaW5nIiwiaW5wdXRUeXBlIjoic2VsZWN0In1dfX0%3D) should have a `year` option in the "Options" section, but it is missing

**To Reproduce**

1. Go to [Playground page for DateTimeFormat](https://www.intl-explorer.com/Playground?locale=en-US&schema=eyJzY2hlbWEiOnsibWV0aG9kIjoiRGF0ZVRpbWVGb3JtYXQiLCJwcmltYXJ5Rm9ybWF0dGVyIjoiZm9ybWF0IiwiaW5wdXRWYWx1ZXMiOlsiMjAyMi0wNC0yNFQxOTowMCIsIjIwMjItMTAtMjRUMTk6MDAiXSwiaW5wdXRWYWx1ZVR5cGUiOiJkYXRlIiwic2Vjb25kYXJ5Rm9ybWF0dGVycyI6WyJmb3JtYXRUb1BhcnRzIiwiZm9ybWF0UmFuZ2UiLCJmb3JtYXRSYW5nZVRvUGFydHMiXSwiaW52YWxpZE9wdGlvbkNvbWJvcyI6eyJkYXRlU3R5bGU6bG9uZyI6WyJkYXkiLCJob3VyIiwibWludXRlIiwic2Vjb25kIiwid2Vla2RheSIsIm1vbnRoIiwiZXJhIiwiZGF5UGVyaW9kIiwidGltZVpvbmVOYW1lIiwiZnJhY3Rpb25hbFNlY29uZERpZ2l0cyJdLCJkYXRlU3R5bGU6ZnVsbCI6WyJkYXkiLCJob3VyIiwibWludXRlIiwic2Vjb25kIiwid2Vla2RheSIsIm1vbnRoIiwiZXJhIiwiZGF5UGVyaW9kIiwidGltZVpvbmVOYW1lIiwiZnJhY3Rpb25hbFNlY29uZERpZ2l0cyJdLCJkYXRlU3R5bGU6bWVkaXVtIjpbImRheSIsImhvdXIiLCJtaW51dGUiLCJzZWNvbmQiLCJ3ZWVrZGF5IiwibW9udGgiLCJlcmEiLCJkYXlQZXJpb2QiLCJ0aW1lWm9uZU5hbWUiLCJmcmFjdGlvbmFsU2Vjb25kRGlnaXRzIl0sImRhdGVTdHlsZTpzaG9ydCI6WyJkYXkiLCJob3VyIiwibWludXRlIiwic2Vjb25kIiwid2Vla2RheSIsIm1vbnRoIiwiZXJhIiwiZGF5UGVyaW9kIiwidGltZVpvbmVOYW1lIiwiZnJhY3Rpb25hbFNlY29uZERpZ2l0cyJdLCJ0aW1lU3R5bGU6bG9uZyI6WyJkYXkiLCJob3VyIiwibWludXRlIiwic2Vjb25kIiwid2Vla2RheSIsIm1vbnRoIiwiZXJhIiwiZGF5UGVyaW9kIiwidGltZVpvbmVOYW1lIiwiZnJhY3Rpb25hbFNlY29uZERpZ2l0cyJdLCJ0aW1lU3R5bGU6ZnVsbCI6WyJkYXkiLCJob3VyIiwibWludXRlIiwic2Vjb25kIiwid2Vla2RheSIsIm1vbnRoIiwiZXJhIiwiZGF5UGVyaW9kIiwidGltZVpvbmVOYW1lIiwiZnJhY3Rpb25hbFNlY29uZERpZ2l0cyJdLCJ0aW1lU3R5bGU6bWVkaXVtIjpbImRheSIsImhvdXIiLCJtaW51dGUiLCJzZWNvbmQiLCJ3ZWVrZGF5IiwibW9udGgiLCJlcmEiLCJkYXlQZXJpb2QiLCJ0aW1lWm9uZU5hbWUiLCJmcmFjdGlvbmFsU2Vjb25kRGlnaXRzIl0sInRpbWVTdHlsZTpzaG9ydCI6WyJkYXkiLCJob3VyIiwibWludXRlIiwic2Vjb25kIiwid2Vla2RheSIsIm1vbnRoIiwiZXJhIiwiZGF5UGVyaW9kIiwidGltZVpvbmVOYW1lIiwiZnJhY3Rpb25hbFNlY29uZERpZ2l0cyJdfSwib3B0aW9ucyI6W3sibmFtZSI6ImRhdGVTdHlsZSIsInZhbHVlVHlwZSI6InN0cmluZyIsImlucHV0VHlwZSI6InNlbGVjdCJ9LHsibmFtZSI6InRpbWVTdHlsZSIsInZhbHVlVHlwZSI6InN0cmluZyIsImlucHV0VHlwZSI6InNlbGVjdCJ9LHsibmFtZSI6ImRheSIsInZhbHVlVHlwZSI6InN0cmluZyIsImlucHV0VHlwZSI6InNlbGVjdCJ9LHsibmFtZSI6ImhvdXIiLCJ2YWx1ZVR5cGUiOiJzdHJpbmciLCJpbnB1dFR5cGUiOiJzZWxlY3QifSx7Im5hbWUiOiJtaW51dGUiLCJ2YWx1ZVR5cGUiOiJzdHJpbmciLCJpbnB1dFR5cGUiOiJzZWxlY3QifSx7Im5hbWUiOiJzZWNvbmQiLCJ2YWx1ZVR5cGUiOiJzdHJpbmciLCJpbnB1dFR5cGUiOiJzZWxlY3QifSx7Im5hbWUiOiJ3ZWVrZGF5IiwidmFsdWVUeXBlIjoic3RyaW5nIiwiaW5wdXRUeXBlIjoic2VsZWN0In0seyJuYW1lIjoibW9udGgiLCJ2YWx1ZVR5cGUiOiJzdHJpbmciLCJpbnB1dFR5cGUiOiJzZWxlY3QifSx7Im5hbWUiOiJlcmEiLCJ2YWx1ZVR5cGUiOiJzdHJpbmciLCJpbnB1dFR5cGUiOiJzZWxlY3QifSx7Im5hbWUiOiJkYXlQZXJpb2QiLCJ2YWx1ZVR5cGUiOiJzdHJpbmciLCJpbnB1dFR5cGUiOiJzZWxlY3QifSx7Im5hbWUiOiJob3VyQ3ljbGUiLCJ2YWx1ZVR5cGUiOiJzdHJpbmciLCJpbnB1dFR5cGUiOiJzZWxlY3QifSx7Im5hbWUiOiJob3VyMTIiLCJ2YWx1ZVR5cGUiOiJib29sZWFuIiwiaW5wdXRUeXBlIjoicmFkaW8ifSx7Im5hbWUiOiJjYWxlbmRhciIsInZhbHVlVHlwZSI6InN0cmluZyIsImlucHV0VHlwZSI6InNlbGVjdCJ9LHsibmFtZSI6ImZyYWN0aW9uYWxTZWNvbmREaWdpdHMiLCJ2YWx1ZVR5cGUiOiJudW1iZXIiLCJpbnB1dFR5cGUiOiJ0ZXh0IiwibWF4IjozLCJtaW4iOjB9LHsibmFtZSI6Im51bWJlcmluZ1N5c3RlbSIsInZhbHVlVHlwZSI6InN0cmluZyIsImlucHV0VHlwZSI6InNlbGVjdCJ9LHsibmFtZSI6InRpbWVab25lTmFtZSIsInZhbHVlVHlwZSI6InN0cmluZyIsImlucHV0VHlwZSI6InNlbGVjdCJ9LHsibmFtZSI6ImxvY2FsZU1hdGNoZXIiLCJ2YWx1ZVR5cGUiOiJzdHJpbmciLCJpbnB1dFR5cGUiOiJzZWxlY3QifSx7Im5hbWUiOiJmb3JtYXRNYXRjaGVyIiwidmFsdWVUeXBlIjoic3RyaW5nIiwiaW5wdXRUeXBlIjoic2VsZWN0In1dfX0%3D).
2. If `DateTimeFormat` is not selected, select it in the `Method` dropdown.
3. Scroll down to the `Options` section.

**Expected behavior**
There should be a `year` dropdown, corresponding to the [`year`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat#year) option in the `DateTimeFormat` constructor options.

**Screenshots**

![Screenshot 2023-04-03 at 5 01 11 PM](https://user-images.githubusercontent.com/1710128/229652450-c4ade05f-a6d7-4c5a-a76f-ba25426d6435.png)

**Desktop (please complete the following information):**

- OS: macOS
- Brave
- Version 1.49.132

**Comment by jesperorb** [comment]
Thank you for the bug report, should be fixed now.
